language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pranshu72001/fib-app -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true pranshu72001/fib-app npm run test

after_success:
  - docker build -t pranshu72001/fib-app-client ./client
  - docker build -t pranshu72001/fib-app-nginx ./nginx
  - docker build -t pranshu72001/fib-app-server ./server
  - docker build -t pranshu72001/fib-app-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pranshu72001/fib-app-client
  - docker push pranshu72001/fib-app-nginx
  - docker push pranshu72001/fib-app-server
  - docker push pranshu72001/fib-app-worker

branches:
  only:
    - main

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Fibonacci-Cacl"
  env: "Fibonacci-Cacl-env"
  bucket_name: "elasticbeanstalk-us-east-1-933377854955"
  bucket_path: "Fibonacci-Cacl"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# http://fibonacci-cacl-env.eba-2mvvvews.us-east-1.elasticbeanstalk.com/